### ISSUE TITLE
Correctly set Cache-Control headers on anything not uploaded to assets/

### ISSUE THREAD

**Issue by kellysutton** [Kerry350/ember-deploy-s3-index#27]
Currently, anything in the store gets the following headers when uploaded using `ember deploy --environment production`:

```
Cache-Control: max-age=63072000, public
Expires: Tue, 01 Jan 2030 00:00:00 GMT
```

This is problematic particularly for the `index.html` file, since it will get cached forever by anything downstream.

This happens when `indexMode` is set to either `"direct"` or `"indirect"`.

This behavior is not present if the assets and index are uploaded, then activated with `ember deploy:activate --revision project:rev --environment production`.

**Expected Result**

Cache headers should be set to 

```
Cache-Control: max-age=0, no-cache
```

when deploying via `ember deploy`.

**Comment by quiddle** [comment]
@kellysutton That's expected behavior. The [ember-deploy-s3](https://github.com/LevelbossMike/ember-deploy-s3) adapter is in charge of uploading assets, which, for better or worse, includes the index.html file. See: https://github.com/ember-cli/ember-cli-deploy#s3-asset-uploads

The `ember-deploy-s3-index` adapter (the one we're commenting on) is in charge of handling what is served when the index file is requested, and does not cache. It sounds like you're deploying both assets and index files to the same s3 bucket, which is not the intent.

**Comment by kellysutton** [comment]
Ah, that is indeed my issue. Thanks for clearing things up. I'll close this issue for now and reopen if I run into any other issues.
